name: Publish AG Components to GitHub Packages
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run the workflow against'
        type: environment
        required: true
  release:
    types: [created]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  publish:
    permissions:
      contents: read
      packages: write
    uses: ArisGlobal/SharedActions/.github/workflows/nodejs-publish.yml@latest
